remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Freelance game translator
description: Looking for a translator to make your game materials accessible to Polish-speaking audiences? Check my portfolio!
show_downloads: false
